blank_issues_enabled: false
contact_links:
  - name: Blockly Forum
    url: https://groups.google.com/forum/#!forum/blockly
    about: The Blockly developer forum, where you can ask and answer questions.
