# This workflow checks that examples can be installed cleanly.
# It only runs on PRs that affect the `examples/` directory.

name: Check examples install status

on: 
  pull_request:
    paths:
      - 'examples/**'

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Check install status
        run: |
          echo "If this step fails, reproduce locally by running `npm run clean:node && cd examples && npx lerna clean --yes` first"
          npm ci
          cd examples && npm ci
